pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL} \n"
                echo "docker image build . -t ecr.com/webserver:${env.BUILD_NUMBER}"
            }
        }
    }
}
