version: "2.1"
services:
  app:
    build: .
    ports:
      - 3001:3000 # 3000 in the container is mapped to 3001 in local host 
  mongo:
    image: mongo
    ports:
      - "27017:27017"
# docker-compose build