name: Change Node JS Version in Runner VM https://github.com/actions/setup-node
on: [pull_request] 
jobs:
    node-version:
        runs-on: ubuntu-latest
        steps:
          - name: Log node version
            run: node -v
          - uses: actions/setup-node@v1
            with:
              node-version: 6
          - name: Log node version
            run: node -v

    
