name: Actions Workflow
on: [push, pull_request]
jobs:
    run-github-actions-job:
        runs-on: ubuntu-latest
        steps:
          - name: Step1-Simple JS Action
            id: greet
            uses: actions/hello-world-javascript-action@v1
            # https://github.com/actions/hello-world-javascript-action
            with:
              who-to-greet: John
          - name: Step2-Log output of Simple JS Action 
            run: echo "${{ steps.greet.outputs.time}}"
          - name: Checkout Action
            uses: actions/checkout@v1
            # https://github.com/actions/checkout
          - name: List files after checkout
            run: |
              pwd
              ls -a
              echo "Commit ID: "  $GITHUB_SHA
              echo "Repository Name:"  $GITHUB_REPOSITORY
              echo "Workspace directory:"  $GITHUB_WORKSPACE
              echo "Token for authentication." ${{ github.token }}
              # git clone git@github:$GITHUB_REPOSITORY
              # git checkout $GITHUB_SHA    