name: Actions Workflow Events Actions 
on: 
  push: 
  pull_request:
    types: [closed, assigned, opened, reopened]
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows 
jobs:
    run-github-actions-job:
        runs-on: ubuntu-latest
        steps:
          - name: List files after checkout
            run: |
              pwd
              ls -a
              echo "Commit ID: "  $GITHUB_SHA