name: Actions Workflow Events Actions 
on: 
  pull_request:
    types: [closed, assigned, opened, reopened]
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows 
jobs:
    run-github-actions-job:
        runs-on: ubuntu-latest
        steps:
          - name: List files after checkout
            run: |
              pwd
              ls -a
              echo "Commit ID: "  $GITHUB_SHA
              echo "Repository Name:"  $GITHUB_REPOSITORY
              echo "Workspace directory:"  $GITHUB_WORKSPACE
              echo "Token for authentication." ${{ github.token }}
              # git clone git@github:$GITHUB_REPOSITORY
              # git checkout $GITHUB_SHA    