name: Secrets 
on: push
env:
  WF_ENV: ${{ secrets.WF_ENV }}
jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV : Available only to all steps in log-env job
      T: ${{ secrets.GITHUB_TOKEN }}  # Can be used to intract with Github API/ Push something to your repo. 
    steps:
      - name: log ENV variables
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"




