name: Secrets 
on: push
env:
  WF_ENV: ${{ secrets.WF_ENV }}
  T: ${{ secrets.GITHUB_TOKEN }}  # Default variable, that can be used to intract with Github API/ Perfrom some action in the repository. 
jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: log ENV variables
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "T: ${T}"




