name: encrypt decrypt files larger than 64 Kb. 
on: push
jobs:
  decrypt:
    runs-on: ububtu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt secret.json.gpg
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/decrypted.json secret.json.gpg 
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE}}
      - name: Print contents of decrypted file
        run: |
          echo $HOME 
          echo $HOME/secret.json 

# https://docs.github.com/en/actions/security-guides/encrypted-secrets#storing-large-secrets
# A secret can only be in size of 64 Kb. 
# GPG Download -  https://gnupg.org/ https://gnupg.org/download/index.html
# GPG command to encrypt       gpg --symmetric --cipher-algo AES256 test.json


