# https://docs.github.com/en/actions/learn-github-actions/expressions#functions 
name: functions workflow
on: push
jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: |
          echo ${{ contains('hello','ll') }}
          echo ${{ startsWith('hello','he') }}
          echo ${{ endsWith('hello','lo') }}
          echo ${{ format('Hello {0} {1} {2}','World','!','!') }}

