name: ENV variable for all jobs
on: push
env:
  WF_ENV: AVAILABLE_TO_ALL_JOBS
jobs:
  log-env:
    runs-on: ubuntu-latest 
      env:
        JOB_ENV : ONLY_AVAILABLE_TO_LOG_ENV_JOB
    steps:
      - name: log ENV variables
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
  






