name: ENV variables
on: push
env:
  WF_ENV: AVAILABLE_TO_ALL_JOBS
jobs:
  log-env:
    runs-on: ubuntu-latest 
    env:
      JOB_ENV : ONLY_AVAILABLE_TO_LOG_ENV_JOB
    steps:
      - name: log ENV variables
        env:
          STEP_ENV : ONLY_AVAILABLE_TO_THIS_STEP
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  






