name: Connector Deployment Validation
on:
  push:
    paths:
    - 'connectors/**'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v36
        id: changed-files
        with:
          include_all_old_new_renamed_files: true    
      - name: validate_file_names
        run: |
          . script.sh; validate_new_files "${{ steps.changed-files.outputs.added_files }}"

