name: Build and Deploy from Main
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      bosunEnvironment: # User Input Option - Will determine which bosun environment to build and deploy to.
        description: 'Bosun Environment?'
        required: false
        default: 'dev'
        type: choice
        options:
          - 'dev'
          - 'stg'
          - 'prd'
  jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List files after checkout
            run: |
              pwd
