name: ConnectorDeploymentWorkflow
env:
  BASE_URL: http://localhost:8083
  USERNAME: test
  PASSWORD: test
on:
  push:
    paths:
    - 'connectors/**'
  pull_request:
    paths:
    - 'connectors/**'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    services:
          app:
            image: landoop/fast-data-dev
            env:
              ADV_HOST: 127.0.0.1         
              RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
              FORWARDLOGS: 0              # Disable running 5 file source connectors that bring application logs into Kafka topics
              SAMPLEDATA: 0  
            ports:
              - 3001:3000 # 3000 in the container is mapped to 3001 in local host
              - 2181:2181                 # Zookeeper
              - 3030:3030                 # Landoop UI
              - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
              - 9581-9585:9581-9585       # JMX Ports
              - 9092:9092                 # Kafka Broker
    steps:
      - name: environment test
        run: |
          echo "${{ vars.BASE_URL }} ${{ vars.CONNECT_REST_BASIC_AUTH_USER }}"
          echo "${{ secrets.CONNECT_REST_BASIC_AUTH_PASSWORD }}"
          pwd
      - name: sleep
        run: |
          sleep 60
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v36
        id: changed-files
        with:
          include_all_old_new_renamed_files: true    
      - name: validate_file_names
        run: |
          . script.sh; validate_files ${{ steps.changed-files.outputs.added_files }} "${{ steps.changed-files.outputs.all_old_new_renamed_files }}"
      - name: Create a test case
        run: |
          curl -X PUT \
          ${BASE_URL}/connectors/gangster/config \
          -H 'Content-Type: application/json' \
          -H 'Accept: application/json' \
          -d '{
          "connector.class": "org.apache.kafka.connect.file.FileStreamSourceConnector",
          "key.converter.schemas.enable": "true",
          "file": "/file-source-standalone-config/demo-file.txt",
          "tasks.max": "2",
          "value.converter.schemas.enable": "true",
          "topic": "file-stream-distributed",
          "value.converter": "org.apache.kafka.connect.json.JsonConverter",
          "key.converter": "org.apache.kafka.connect.json.JsonConverter"
          }'
      - name: Create / Update connectors
        run: |
          added_modified_files="${{ steps.changed-files.outputs.added_files }} ${{ steps.changed-files.outputs.modified_files }}"
          for file in $added_modified_files; do
            if  [[ $file == connectors* ]] && [[ $file == *.json ]] ;
            then
              CONNECTOR_NAME=`echo $file | rev |  cut -d/ -f1 | rev | cut -d. -f1`
              URL=`echo ${BASE_URL}/connectors/${CONNECTOR_NAME}/config`
              response=$(curl --write-out '%{http_code}' --silent --output /dev/null -u $USERNAME:$PASSWORD -i -X PUT -H  "Content-Type:application/json" $URL -d `jq -c . < $file`)
              echo $response 
              if [ $response == 201 ]
              then
                echo "Created: $CONNECTOR_NAME"
              fi
              if [ $response == 200 ]
              then
                echo "Updated: $CONNECTOR_NAME"
              fi
            fi
          done
      - name: Delete connectors
        run: |
          for file in ${{ steps.changed-files.outputs.deleted_files }}; do
            if  [[ $file == connectors* ]] && [[ $file == *.json ]] ;
            then
              . script.sh; delete_connector $file $BASE_URL ${{ vars.CONNECT_REST_BASIC_AUTH_USER }} ${{ secrets.CONNECT_REST_BASIC_AUTH_PASSWORD }}
              #bash -c "source ./script.sh; delete_connector $file $BASE_URL ${{ vars.CONNECT_REST_BASIC_AUTH_USER }} ${{ secrets.CONNECT_REST_BASIC_AUTH_PASSWORD }}"
              #echo $(bash -c "source ./script.sh; delete_connector $file $BASE_URL ${{ vars.CONNECT_REST_BASIC_AUTH_USER }} ${{ secrets.CONNECT_REST_BASIC_AUTH_PASSWORD }}") || exit 1

              # CONNECTOR_NAME=`echo $file | rev |  cut -d/ -f1 | rev | cut -d. -f1`
              # DELETE_URL=`echo ${BASE_URL}/connectors/${CONNECTOR_NAME}`
              # response=$(curl --write-out '%{http_code}' --silent --output response.txt -u ${{ vars.CONNECT_REST_BASIC_AUTH_USER }}:${{ secrets.CONNECT_REST_BASIC_AUTH_PASSWORD }} -s -X DELETE $DELETE_URL)
              # echo $response
              # if [ $response == 204 ]
              # then
              #   echo "Deleted: $CONNECTOR_NAME"
              # else
              #   cat response.txt
              # fi
            fi
          done
      - name: Delete old connector and Create new connector(file renamed)
        run: |
          for file in ${{ steps.changed-files.outputs.all_old_new_renamed_files }}; do
            IFS=',' read -r -a array <<< "$file" 
            if  [[ ${array[0]}  == connectors* ]] && [[ ${array[0]}  == *.json ]] && [[ ${array[1]}  == connectors* ]] && [[ ${array[1]}  == *.json ]];
            then
              OLD_CONNECTOR_NAME=`echo ${array[0]} | rev |  cut -d/ -f1 | rev | cut -d. -f1`
              DELETE_URL=`echo ${BASE_URL}/connectors/${OLD_CONNECTOR_NAME}`
              response=$(curl --write-out '%{http_code}' --silent --output /dev/null -u $USERNAME:$PASSWORD -s -X DELETE $DELETE_URL)
              echo $response
              if [ $response == 204 ]
              then
                echo "Deleted: $OLD_CONNECTOR_NAME"
              fi
            
              NEW_CONNECTOR_NAME=`echo ${array[1]} | rev |  cut -d/ -f1 | rev | cut -d. -f1`
              CREATE_URL=`echo ${BASE_URL}/connectors/${NEW_CONNECTOR_NAME}/config`
              response=$(curl --write-out '%{http_code}' --silent --output /dev/null -u $USERNAME:$PASSWORD -i -X PUT -H  "Content-Type:application/json" $CREATE_URL -d `jq -c . < ${array[1]}`)
              echo $response 
              if [ $response == 201 ]
              then
                echo "Created: $NEW_CONNECTOR_NAME"
              fi  
            fi
          done