name: Build and deploy from Main1
on: 
  push: # pull_request 
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This checks out the required branch of your repo (master in this case)
      - uses: actions/checkout@v3