name: Connector Deployment Workflow
on:
  push:
    paths: # Runs when we only change the files that matches the paths. 
    - 'connectors/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: list changed files
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }} 
    