name: Connector Deployment Workflow
on:
  push:
    paths:
    - 'connectors/**'
  #workflow_dispatch:
  pull_request:
    paths:
    - 'connectors/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v36
        id: changed-files
        with:
          include_all_old_new_renamed_files: true
      - name: Create connectors
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was added"
            echo "$file" | rev |  cut -d/ -f1 | rev | cut -d. -f1
          done
      - name: List all modified files
        run: |
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            echo "$file was modified."
          done
      - name: List all deleted files
        run: |
          for file in ${{ steps.changed-files.outputs.deleted_files }}; do
            echo "$file was deleted."
          done
      - name: List all renamed files 
        run: |
          for file in ${{ steps.changed-files.outputs.all_old_new_renamed_files }}; do
            echo "$file was renamed."
            IFS=',' read -r -a array <<< "$file"
            echo "Old file : ${array[0]}"
            echo "New file : ${array[1]}"
          done

      
      - name: Get Users
        run: "curl -X GET http://google.co.uk" 
   
    