name: Connector Deployment Workflow
on:
  push:
    paths: # Runs when we only change the files that matches the paths. 
    - 'connectors/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

          
