name: Build and Deploy from Main
on:
  push:
    branches: [main]
    paths-ignore: # Runs when we only change the files that matches the paths. 
    - 'connectors/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This checks out the required branch of your repo (master in this case)
      - uses: actions/checkout@v3