name: Connector Deployment Workflow
on:
  push:
    paths: # Runs when we only change the files that matches the paths. https://github.com/marketplace/actions/get-all-changed-files 
    - 'connectors/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #- uses: jitterbit/get-changed-files@v1
        #id: abc
        #with:
          #token: ${{ secrets.GITHUB_TOKEN }}
          #format: space-delimited 
      #- name: list changed files
        #run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      #- name: Print Added Files from J
        #run: |
          #echo "Files Added:"
          # echo "Added files:"
          # git diff --name-only --diff-filter=A HEAD^
          # echo "deleted files"
          # git diff --name-only --diff-filter=D HEAD^ 
          # echo "updated files"
          # git diff --name-only --diff-filter=M HEAD^
      #- name: Printing
        #run: |
          #echo "All:"
          #echo "${{ steps.abc.outputs.all }}"
          #echo "Added:"
          #echo "${{ steps.abc.outputs.added }}"
          #echo "Removed:"
          #echo "${{ steps.abc.outputs.removed }}"
          #echo "Modified:"
          #echo "${{ steps.abc.outputs.modified }}"
          #cat ${{ steps.abc.outputs.modified }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
          include_all_old_new_renamed_files: true
      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was added"
          done
      - name: List all modified files
        run: |
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            echo "$file was modified."
          done
      - name: List all deleted files
        run: |
          for file in ${{ steps.changed-files.outputs.deleted_files }}; do
            echo "$file was deleted."
          done
      - name: List all renamed files 
        run: |
          echo ${{ steps.changed-files.all_old_new_renamed_files }}
      - name: Get Users
        run: "curl -X GET http://google.co.uk" 
   
    