name: Connector Deployment Workflow
env:
  environment: dev
  CONNECT_URL: http://localhost:8083
  BASE_URL: http://localhost:8083
  USERNAME: test
  PASSWORD: test
on:
  push:
    paths:
    - 'connectors/**'
  pull_request:
    paths:
    - 'connectors/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v36
        id: changed-files
        with:
          include_all_old_new_renamed_files: true
      - name: Create / Update connectors
        run: |
          array = (${{ steps.changed-files.outputs.added_files[@] }} ${{ steps.changed-files.outputs.modified_files[@] }})
          echo ${array[@]}
       
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            CONNECTOR_NAME=`echo $file | rev |  cut -d/ -f1 | rev | cut -d. -f1`
            URL=`echo ${CONNECT_URL}/connectors/${CONNECTOR_NAME}/config`
            # curl -u $USERNAME:$PASSWORD -i -X PUT -H  "Content-Type:application/json" $URL -d `jq -c . < $file`
            # response=$(curl --write-out '%{http_code}' --silent --output /dev/null -u $USERNAME:$PASSWORD -i -X PUT -H  "Content-Type:application/json" $URL -d `jq -c . < $file`)
            # echo $response 
          done

          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            CONNECTOR_NAME=`echo $file | rev |  cut -d/ -f1 | rev | cut -d. -f1`
            URL=`echo ${CONNECT_URL}/connectors/${CONNECTOR_NAME}/config`
            # curl -u $USERNAME:$PASSWORD -i -X PUT -H  "Content-Type:application/json" $URL -d `jq -c . < $file`
            # response=$(curl --write-out '%{http_code}' --silent --output /dev/null -u $USERNAME:$PASSWORD -i -X PUT -H  "Content-Type:application/json" $URL -d `jq -c . < $file`)
            # echo $response 
          done
      - name: Delete connectors
        run: |
          for file in ${{ steps.changed-files.outputs.deleted_files }}; do
            CONNECTOR_NAME=`echo $file | rev |  cut -d/ -f1 | rev | cut -d. -f1`
            DELETE_URL=`echo ${BASE_URL}/connectors/${CONNECTOR_NAME}`
            # curl -s -X DELETE $DELETE_URL
          done
      - name: Delete old connector and Create new connector(file renamed)
        run: |
          for file in ${{ steps.changed-files.outputs.all_old_new_renamed_files }}; do
            IFS=',' read -r -a array <<< "$file"
            OLD_CONNECTOR_NAME=`echo ${array[0]} | rev |  cut -d/ -f1 | rev | cut -d. -f1`
            DELETE_URL=`echo ${BASE_URL}/connectors/${OLD_CONNECTOR_NAME}`
            # curl -s -X DELETE $DELETE_URL
            
            NEW_CONNECTOR_NAME=`echo ${array[1]} | rev |  cut -d/ -f1 | rev | cut -d. -f1`
            CREATE_URL=`echo ${BASE_URL}/connectors/${NEW_CONNECTOR_NAME}/config`
            # curl -u $USERNAME:$PASSWORD -i -X PUT -H  "Content-Type:application/json" $CREATE_URL -d `jq -c . < ${array[1]}`
          done
   
    